FROM gcc:latest

ARG PORT
ARG PASSWORD

RUN apt-get update && \
    apt-get install -y ruby

RUN git clone --depth 1 https://github.com/plonk/peercast-yt.git

WORKDIR peercast-yt/ui/linux

RUN make

RUN cp ../../bvt/peercast.ini.master peercast.ini && \
    sed -i -e "s/^serverPort = \(.*\)/serverPort = ${PORT}/" peercast.ini && \
    sed -i -e "s/^isRoot = \(.*\)/isRoot = Yes/" peercast.ini && \
    sed -i -e "s/^password = \(.*\)/password = ${PASSWORD}/" peercast.ini

CMD ["./peercast"]
