[yp]
    yp_name = "035p"
	PortCheck = true                # ポートチェックの有無
	PortCheckDefOff = true 			# モード選択記号がない場合にポートチェックを使うか否か
	SpeedCheck = true               # 帯域チェックの有無
	MossoLine = 2000                # 低速・高速回線の判断基準
	CheckIntervalPass = 60*11	    # ポートチェックの間隔 Pass時
	CheckIntervalReject = 15		# ポートチェックの間隔 Rejected時

[database]
    host = "yayp-mariadb"
    port = "3306"
    dbname = yayp
    user = root
    pass = password

[peercast]
    port = "7145"
    host = "yayp-peercast"

[site]
    title = "Yet Another PeerCast Yellow Pages"
	myDomain = 'www.mydomain.com'
	ShowChannels = 10                # １ページに表示するチャンネル数
