[yp]
    yp_name = "mp"
	SpeedCheck = true               # 帯域チェックの有無
	MossoLine = 2000                # 低速・高速回線の判断基準
    title = "Yet Another PeerCast Yellow Pages"
	myDomain = "www.mydomain.com"
	ShowChannels = 10                # １ページに表示するチャンネル数

[database]
    host = "yayp-mariadb"
    port = "3306"
    dbname = yayp
    user = root
    pass = password

[peercast]
    port = "7145"
    host = "yayp-peercast"
