[server]
    YPPrefix = "mp"
    Port     = "8000"
    LogPath  = "logs/yp.log"
    Debug    = true

[database]
    Host     = "localhost"
    Port     = "3306"
    User     = "root"
    Password = "password"
    DB       = "yayp"

[peercast]
    Host         = "localhost"
    Port         = "7145"
    AuthType     = "basic"
    AuthUser     = "root"
    AuthPassword = "peer"
