[yp]
    prefix = "mp"

[database]
    host   = "localhost"
    port   = "3306"
    user   = "root"
    password = "password"
    db     = "yayp"

[peercast]
    port   = "7145"
    host   = "yayp-peercast"
