[server]
    Port     = "8000"
    YPPrefix = "mp"

[database]
    Host     = "localhost"
    Port     = "3306"
    User     = "root"
    Password = "password"
    DB       = "yayp"

[peercast]
    Host         = "localhost"
    Port         = "7145"
    Auth         = "basic"
    AuthUser     = "root"
    AuthPassword = "peer"
